apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig-deployment
  labels:
    app: xmrig
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      containers:
      - name: xmrig
        image: wentzien/xmrig:1.0.1
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/lib/modules"
          name: moduleslib
      volumes:
      - name: moduleslib
        hostPath:
          path: "/lib/modules"
      